# Web Server Configuration
server.port=8081

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8ns9i48aovs739i23hg-a.virginia-postgres.render.com:5432/newauditdb
spring.datasource.username=postgres_user
spring.datasource.password=8R5JejVJMPSIkk58PJZzS5aumXDBtVXR
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Node.js Log Service URL
nodejs.service.url=https://nodejs-1-lrxn.onrender.com
